<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IXModularityProjectRole>ArchitectureTest</IXModularityProjectRole>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnitV3" />
  </ItemGroup>
</Project>
